/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Subject = IDL.Variant({
  'all' : IDL.Null,
  'maths' : IDL.Null,
  'english' : IDL.Null,
  'science' : IDL.Null,
});
export const Mode = IDL.Variant({ 'offline' : IDL.Null, 'online' : IDL.Null });
export const Inquiry = IDL.Record({
  'subject' : Subject,
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'preferredMode' : Mode,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getDemoBookingCount' : IDL.Func([], [IDL.Nat], ['query']),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), Subject, Mode, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Subject = IDL.Variant({
    'all' : IDL.Null,
    'maths' : IDL.Null,
    'english' : IDL.Null,
    'science' : IDL.Null,
  });
  const Mode = IDL.Variant({ 'offline' : IDL.Null, 'online' : IDL.Null });
  const Inquiry = IDL.Record({
    'subject' : Subject,
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'preferredMode' : Mode,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getDemoBookingCount' : IDL.Func([], [IDL.Nat], ['query']),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), Subject, Mode, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };